### ISSUE TITLE
Error parsing go.mod

### ISSUE THREAD

**Issue by lamarios** [tfkhdyt/auto-epp-go#1]
Hi,

I've been trying to build a package for NixOS but when i build your project i'm facing the following:

```
go: errors parsing go.mod:
/build/source/go.mod:3: invalid go version '1.21.0': must match format 1.23
```

Do you know how to solve this ?

**Comment by tfkhdyt** [comment]
Fixed in https://github.com/tfkhdyt/auto-epp-go/commit/c76ad23f7d6a2a2433a28d489880d91799cd3763

But hey, I recommend you to use the [Rust port](https://github.com/tfkhdyt/auto-epp-rs) instead

**Comment by lamarios** [comment]
ok thanks. Noted on the rust version.
